### PR TITLE
point to new repo location

### PR DESCRIPTION
**Pull request by techknowlogick**
Watchtower repo has moved

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks, but the Dockerfiles within the docker/ folder still contain the old home :)

**Comment by techknowlogick** [comment]
I don't see a `docker/` folder in this repo.

**Comment by tboerger** [comment]
Sorry, `latest/` of course.

**Comment by techknowlogick** [comment]
I'm not sure what you mean. I've updated all the dockerfiles I could find.

**Pull request merged**
